In [1]:
import numpy as  np
import matplotlib.pyplot as plt 
import pandas as pd 
from keras.datasets import mnist

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()
print(X_train)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [13]:
X_train = X_train.reshape(X_train.shape[0], 28, 28, 1)
X_test = X_test.reshape(X_test.shape[0], 28, 28, 1)
input_shape = (28, 28, 1)
from  tensorflow.keras.utils import to_categorical
# convert class vectors to binary class matrices
num_classes = 10
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

X_train = X_train.astype('float32')
X_test = X_test.astype('float32')
X_train /= 255
X_test /= 255
print('x_train shape:', X_train.shape)
print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

x_train shape: (60000, 28, 28, 1)
60000 train samples
10000 test samples


In [14]:
from keras.layers import (
    Conv2D, Dense, MaxPooling2D, Dropout, Flatten
)
from keras.models import Sequential
from keras.losses import (
    categorical_crossentropy, binary_crossentropy
)
from tensorflow.keras.optimizers import Adadelta
batch_size = 128
epoch = 10
input_shape = X_train[0].shape

model = Sequential()
model.add(Conv2D(
    32, kernel_size=(3, 3),activation='relu',input_shape = (28,28,1)
))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(rate=0.25))
model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(rate=0.5))
model.add(Dense(10, activation='softmax'))
model.compile(loss=binary_crossentropy,optimizer=Adadelta(),metrics=['accuracy'])
model.summary()


Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_6 (Conv2D)           (None, 26, 26, 32)        320       
                                                                 
 conv2d_7 (Conv2D)           (None, 24, 24, 64)        18496     
                                                                 
 max_pooling2d_3 (MaxPooling  (None, 12, 12, 64)       0         
 2D)                                                             
                                                                 
 dropout_6 (Dropout)         (None, 12, 12, 64)        0         
                                                                 
 flatten_3 (Flatten)         (None, 9216)              0         
                                                                 
 dense_6 (Dense)             (None, 256)               2359552   
                                                      

In [15]:
hist = model.fit(X_train, y_train,batch_size=128,epochs=10,verbose=1,validation_data=(X_test, y_test))
print("The model has successfully trained")

model.save('mnist.h5')
print("Saving the model as mnist.h5")

Epoch 1/10
469/469 [==============================] - 204s 431ms/step - loss: 0.6704 - accuracy: 0.1455 - val_loss: 0.6407 - val_accuracy: 0.2153
Epoch 2/10
469/469 [==============================] - 237s 506ms/step - loss: 0.6023 - accuracy: 0.1496 - val_loss: 0.5437 - val_accuracy: 0.2134
Epoch 3/10
469/469 [==============================] - 212s 453ms/step - loss: 0.4840 - accuracy: 0.1480 - val_loss: 0.4039 - val_accuracy: 0.2206
Epoch 4/10
469/469 [==============================] - 221s 471ms/step - loss: 0.3798 - accuracy: 0.1517 - val_loss: 0.3337 - val_accuracy: 0.2855
Epoch 5/10
469/469 [==============================] - 235s 500ms/step - loss: 0.3448 - accuracy: 0.1633 - val_loss: 0.3170 - val_accuracy: 0.4005
Epoch 6/10
469/469 [==============================] - 206s 439ms/step - loss: 0.3348 - accuracy: 0.1838 - val_loss: 0.3098 - val_accuracy: 0.4852
Epoch 7/10
469/469 [==============================] - 209s 446ms/step - loss: 0.3280 - accuracy: 0.2076 - val_loss: 0.3036 -

In [18]:
score_validation = model.evaluate(X_test,y_test, verbose=0)
print(score_validation[1])
score_train = model.evaluate(X_train, y_train, verbose=0)
print(score_train[1])

0.6984000205993652
[0.28437232971191406, 0.6903499960899353]
